#!/bin/bash

# EXPORTS

export EDITOR='nvim'
export VISUAL='nvim'

# ALIASES

alias k=kubectl
alias cdg='cd $(git rev-parse --show-toplevel)'
alias interlink='cd /home/niels/repos/interlink'
alias ngcp='cd /home/niels/repos/ngcp'
alias smartconnect='cd /home/niels/repos/smartconnect'
alias repos='cd /home/niels/repos'
alias gitconfig-pers='cp ~/.git-credentials-pers ~/.git-credentials && cp ~/.config/bash-config/gitconfig/.gitconfig.pers ~/.gitconfig'
alias gitconfig-work='cp ~/.git-credentials-work ~/.git-credentials && cp ~/.config/bash-config/gitconfig/.gitconfig.work ~/.gitconfig'

# STATUS LINE

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\u \[\e[1;32m\]\w \[\e[1;91m\]\$(parse_git_branch)\[\e[1;00m\] "

#ASDF

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
